blueprint:
  name: Sonoff SBZ-03 Motion sensor light on/off with delay
  description: Turn on lights when motion is detected, and turn them off after a configurable delay when no motion is detected.
  domain: automation
  input:
    motion_sensor:
      name: Motion Sensor
      description: Select the motion sensor (binary sensor) that will trigger the lights.
      selector:
        entity:
          domain: binary_sensor
          device_class: occupancy
    target_lights:
      name: Target Lights
      description: Select one or more lights to turn on/off.
      selector:
        target:
          entity:
            domain: 
              - light
              - switch
    delay_time:
      name: Delay Time
      description: The time to wait (in minutes) after no motion is detected before turning off the lights.
      default: 1
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: minutes

trigger:
  - platform: state
    entity_id: !input motion_sensor
    to: "on"
  - platform: state
    entity_id: !input motion_sensor
    to: "off"

action:
  - choose:
      # If the motion sensor turns on, turn on the lights
      - conditions:
          - condition: state
            entity_id: !input motion_sensor
            state: "on"
        sequence:
          - service: homeassistant.turn_on
            target: !input target_lights
      # If the motion sensor turns off, wait for the specified delay and then turn off the lights
      - conditions:
          - condition: state
            entity_id: !input motion_sensor
            state: "off"
        sequence:
          - delay: 
              minutes: !input delay_time
          - service: homeassistant.turn_off
            target: !input target_lights

mode: restart
